// Code generated by "stringer -type=RuneType ../src/enums/runetype/runetype.go"; DO NOT EDIT.

package runetype

import "strconv"

const _RuneType_name = "InvalidDigitLetterPoundParenthesisOperatorEOF"

var _RuneType_index = [...]uint8{0, 7, 12, 18, 23, 34, 42, 45}

func (i RuneType) String() string {
	if i < 0 || i >= RuneType(len(_RuneType_index)-1) {
		return "RuneType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RuneType_name[_RuneType_index[i]:_RuneType_index[i+1]]
}
