// Code generated by "stringer -type=RuneType"; DO NOT EDIT.

package runetype

import "strconv"

const _RuneType_name = "InvalidSpaceDigitLetterPoundParenthesisOperatorEOF"

var _RuneType_index = [...]uint8{0, 7, 12, 17, 23, 28, 39, 47, 50}

func (i RuneType) String() string {
	if i < 0 || i >= RuneType(len(_RuneType_index)-1) {
		return "RuneType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RuneType_name[_RuneType_index[i]:_RuneType_index[i+1]]
}
