// Code generated by "stringer -type=TokenType ../src/enums/tokentype/tokentype.go"; DO NOT EDIT.

package tokentype

import "strconv"

const _TokenType_name = "NumberVariableParenthesisOperatorEOF"

var _TokenType_index = [...]uint8{0, 6, 14, 25, 33, 36}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
